server:
  port: 9000

spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/spring-course
    password: 1qa2ws3ed
    username: postgres
    pool-name: ManagerPool
    min-pool-size: 1
    max-pool-size: 3
    max-lifetime: 1800000
    validation-timeout: 250
    allow-bean-definition-overriding: true
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
