loggin:
  level:
    com:
      project: DEBUG
# Propriedades do Banco de dados em ambiente de Desenv

# Configurações do Spring JPA
spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/spring-course
    password: 1qa2ws3ed
    username: postgres
    pool-name: ManagerPool
    min-pool-size: 1
    max-pool-size: 3
    max-lifetime: 1800000
    validation-timeout: 250
    allow-bean-definition-overriding: true
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid´
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000
  mail:
    host: smtp.mailtrap.io
    port: 2525
    ssl: no
    tls: yes
    username: ${MAIL_USERNAME:78302434ca5131}
    password: ${MAIL_PASSWORD:27dd472444306f}
    protocol: smtp


server:
  port: 8080

  #-Dspring.profiles.active=dev
